### ISSUE TITLE
Implement all flag for cli.py

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#112]
Add an `--all` flag in `cli.py` so we don't have to specify names of all the states to run.

Use [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/) to read contents of `warn.scrapers`, with additional logic to ensure that we're limiting to modules with two-letter state postal codes.

```bash
importlib.resources.contents('warn.scrapers')
```

**Comment by palewire** [comment]
This is complete.
