### ISSUE TITLE
Fix AL scrape

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#115]
The Alabama scraper works but includes in the final output CSV that appears to be dirty. The rows in question (see image below) can be found at the bottom of the state's [layoff listings page](https://www.madeinalabama.com/warn-list/), but we'll need to research what these rows mean and possibly update `warn.scrapers.al.py` to discard them.

![Screen Shot 2021-06-23 at 7 08 19 PM](https://user-images.githubusercontent.com/39200/123191958-e047a600-d456-11eb-8252-5f319366ba9c.png)

**Comment by palewire** [comment]
Is this ticket still active?

**Comment by ydoc5212** [comment]
We have had a hard time getting ahold of AL officials to fix the data on their end, so we added a hard-coded regex to remove the erroneous data for now. This means the issue should be fixed for now. 
(In the future, we will need to remove this hard-coded fix if/when AL changes systems; the regex removes all rows that dont have a value that starts with "clos" or "lay" in the first column.)

@zstumgoren do you think we can close this?

**Comment by zstumgoren** [comment]
If the AL officials are still not responding and we're confident the code fix discards only these few garbage rows, I'm fine with closing this issue. @palewire if you're in agreement, feel free to do the honors
