### ISSUE TITLE
Fix MT: Find out why we don't get more recent data

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#132]
> Related to #233 

MT data is available via an Excel file from the MT Labor & Industry Department:

https://wsd.dli.mt.gov/wioa/related-links/warn-notice-page

The data in the Excel file, which our scraper relies on, limited to 2015-2020. 

We should call the MT agency to determine if more recent data (for 2021) is available and, if so, how to acquire it. And document that status.

**Comment by zstumgoren** [comment]
The MT WARN Excel file contains a single record for 2021 (see screenshot). So it's possible that they *do* keep the data up-to-date, but there simply are not a high volume of notices. We should confirm this with the state before closing this ticket.

<img width="776" alt="Screen Shot 2021-11-16 at 2 30 50 PM" src="https://user-images.githubusercontent.com/39200/142078170-7812a07b-9dac-4ce2-86a1-3c99a7ac291f.png">

**Comment by chriszs** [comment]
That theory seems consistent with observed patterns:

<img width="86" alt="Screen Shot 2022-02-20 at 1 14 42 AM" src="https://user-images.githubusercontent.com/1103467/154831022-9bf753c6-a4a2-4993-8241-41eac54edc4c.png">

**Comment by palewire** [comment]
I've left a voicemail from the listed MT officer and also sent an email.

**Comment by palewire** [comment]
MT just emailed me back. They said:

>Hi Ben,
> Yes the list is up to date.  The label on the website just hasn't been updated yet.
> Good luck on your research.
> Candi

That means we can close this ticket.
