### ISSUE TITLE
Fix NE: Find out why we don't get more recent data

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#133]
The Nebraska scraper only grabs data through 9/20. The NE site doesn't appear to contain 2021 data, but we need to research and document if, e.g., the state has stopped posting WARN notices or determine if they've begun posting the data elsewhere.

Also, the pandas code used to write the data appears to be including the index (left-most column in the exported CSV), which needs to be removed.

**Comment by palewire** [comment]
This file is cleaned up by #359 but it doesn't address the issue that we're not getting fresh data.

**Comment by chriszs** [comment]
Some 2020 notices posted [here](https://dol.nebraska.gov/ReemploymentServices/LayoffServices/LayoffsAndDownsizingWARN), but almost nothing from 2021.

**Comment by palewire** [comment]
I emailed the generic address on that site.

**Comment by palewire** [comment]
I got this email.

> Hello:
>
> I received your inquiry regarding WARN Act data.  What media outlet do you represent?  I am not aware of any WARN notices received that have not been posted, but encourage you to keep checking our website for the latest information.  If there is a specific company you are interested in, let me know.  Or you may check with the US Department of Labor: https://www.dol.gov/agencies/eta/layoffs/warn

> Grace Johnson, CLSSEGB 
> Marketing & Communications Specialist
> Nebraska Department of Labor
> 550 South 16th Street
> Lincoln, NE 68508
> OFFICE  402-471-4189
> CELL  402-890-8947
> [grace.johnson@nebraska.gov](mailto:grace.johnson@nebraska.gov)
> [dol.nebraska.gov](http://dol.nebraska.gov/)  |  [Facebook](https://www.facebook.com/Nebraska.DOL)  |  [Twitter](https://twitter.com/NE_DOL)

**Comment by palewire** [comment]
I do some some 2021 notices on this page, which I don't think we're scraping. We might need to reconcile it in.

https://dol.nebraska.gov/ReemploymentServices/LayoffServices/LayoffsAndDownsizingWARN
