### ISSUE TITLE
Fix NJ scrape

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#135]
NJ contains encoding errors in certain records, mainly from 2005-2007 depending on the scraper run. 

For example, from a recent copy of `newjersey_warn_raw.csv` downloaded from the platform project:

```
MAYNE PHARMAÂ,PARAMUSÂ,4/6/07Â,67Â
```

Records can be found by opening in Excel and reverse-sorting on `EFFECTIVEDATE` field.

**Comment by palewire** [comment]
This is a duplicate for #156
