### ISSUE TITLE
Fix OR: Figure out how to get more recent data

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#139]
The Oregon scraper currently pages through HTML on the state warn site:

https://ccwd.hecc.oregon.gov/Layoff/WARN

The site also offers downloadable Excel files, which we can likely scrape using session-based requests. This could dramatically simplify and speed up the scrape. However, there are some differences between these data sources that we need to investigate.

The HTML listings do not contain all the fields contained in the Excel downloads. Further, the HTML tables appear to be less up-to-date than the Excel files, and there are discrepancies in the records between these sources. 

The HTML listings go back to the mid-90s in terms of coverage, whereas the Excel file only goes back to around 2011. 

We should call the OR folks who manage the data to determine:

1) which is the more accurate source for current and recent data
2) if the older historical data can be obtained in a machine-readable format without having to bother with the web scrape

**Comment by ydoc5212** [comment]
i added our historical document scraping strategy to the OR scraper and commented out code for website scraping, since the historical goes much farther back and includes more detailed data. as we decide on OR scraping strategy we could continue requesting historical data from OR as serdar suggests, or could implement a 'merge' between a scrape of the current website and the historical document.
(#241)

**Comment by zstumgoren** [comment]
@ydoc5212 Hey there. Thanks for picking up the thread on this. Let's chat before merging any updates to OR code just to make sure we're on same page about strategy

**Comment by palewire** [comment]
If OR is historical only, is it worth including our system?

**Comment by stucka** [comment]
Looks like there's a token in a form here:
https://ccwd.hecc.oregon.gov/Layoff/WARN/Download

Token gets POSTed with a standardized sorting option and a format (e.g., PDF or either of two Excel formats).

That form gets POSTed again with some cookies. Newest version of the page gets a link to an Excel file.

**Comment by stucka** [comment]
Have ugly code to get Excel URL.
`from bs4 import BeautifulSoup
import requests

starturl = "https://ccwd.hecc.oregon.gov/Layoff/WARN/Download"
baseurl = "https://ccwd.hecc.oregon.gov"

r = requests.get(starturl)

cookies = r.cookies

soup = BeautifulSoup(r.content)

# Looking for something like <input name="__RequestVerificationToken" type="hidden" value="GYlfHSHzATg5x9TZgIe...
tokenname = "__RequestVerificationToken"
tokenvalue = soup.find("input", {"name":tokenname})['value']

payload = {
    tokenname: tokenvalue,
    "WARNFormat": "xlsx",
    "WARNSort": "LOT4",
}

headers = {
    "Host": "ccwd.hecc.oregon.gov",
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0",
    "Origin": "https://ccwd.hecc.oregon.gov",
    "Referer": "https://ccwd.hecc.oregon.gov/Layoff/WARN/Download",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Content-Type": "application/x-www-form-urlencoded",
    "Connection": "keep-alive",
    }

r = requests.post(starturl, cookies=cookies, data=payload, headers=headers)

dlsoup = BeautifulSoup(r.content)

excelurl = baseurl + dlsoup.find("a", {"target": "_blank", "class": "btn-primary"})['href']`

**Comment by stucka** [comment]
I'll try to grab this in the coming days. Note we've got a spreadsheet going back to 1980, while the online version covers roughly 10 years. It could be helpful to merge the two, but 10 years of data is also great. Spreadsheet link here https://github.com/biglocalnews/warn-scraper/issues/139#issuecomment-880248141
