### ISSUE TITLE
Platform and project metadata and tasks house-cleaning

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#149]
A number of files on the platform were previously managed manually but have not been updated recently. Some of these manually managed files have since been migrated to automated updates using this WARN scraper. Additionally, some stray ETL-related file artifacts have crept into the project.

Time to do some housing-cleaning to bring all our metadata up to date and clean up unneeded files from the platform project. 

- [ ] Update the [WARN metadata spreadsheet][]
- [ ] Update Project Board to align with metadata spreadsheet (create tickets where needed)
- [ ] Back up all current files from production project bucket to the data-etl bucket using project ID
- [ ] Delete all files that are duplicates or ETL-related file artifacts. Leave the files that were manually updated, but create tickets to automate data acquisition.
- [ ] Add a disclaimer to project description saying we're in the process of updating scrapers and data files, so approach the data with caution

[WARN metadata spreadsheet]: https://docs.google.com/spreadsheets/d/1rQ_PMQZbwQQxBRDCIzBbIJrsiI6JraoYoEWrCvDZMe8/edit#gid=1679145335

**Comment by palewire** [comment]
I am going to solve one issue here with #327.
