### ISSUE TITLE
Add checklist for state tasks to README

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#173]
Could be useful to add a checklist to the README that mentions common tasks when working on a state:

- Add debug-level logging for at least the web request
- Apply the conventions for writing files to `cache/` and `exports/` dirs
- Apply `write_rows_to_csv` if applicable
- Generally DRY up the code
- what else?

**Comment by palewire** [comment]
What are the conventions for writing files to cache and exports? Is there an existing scraper you would point to as the ideal?

**Comment by palewire** [comment]
> Add debug-level logging for at least the web request

This was done with #298 

> Apply the conventions for writing files to cache/ and exports/ dirs

This was done in https://github.com/biglocalnews/warn-scraper/commit/38aab0f0ab5da858af04fc0cae9853881bc98ccb

> Apply write_rows_to_csv if applicable

In the docs as well
