### ISSUE TITLE
Keep Non-Warn records for Job Center sites?

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#179]
Our [Job Center](https://github.com/biglocalnews/WARN/blob/main/docs/job_center.md) scrapers (#126) capture Non-WARN layoff notices in a number of states. In Arizona, the site displays WARN and Non-WARN notices, whereas in Kansas, these records are not displayed on a basic web search but the nature of our scraping approach manages to capture them regardless.

Our counts appear correct, i.e.:

- there are no dupes
- our count of WARN notices matches the expected count from the web search listings as well as the number captured by the current (legacy) scraper
- a sampling of detail page links all work (i.e. are valid records)

The open question is whether we *should* provide these records to end users on the platform. Our export CSVs currently retain them, and it would be easy enough to document the need for end users to filter these records for stories focusing exclusively on WARN.

As part of this decision, we should put in a call to the Job Center to get a better understanding of these records and determine if there's a compelling a reason to *not* provide them to end users.

**Comment by chriszs** [comment]
Flagging that current combined CSV doesn't retain this categorization.

**Comment by zstumgoren** [comment]
@chriszs @palewire Dropping non-WARN from the data posted to the platform seems highly reasonable. Closing this ticket but feel free to re-open if you think it requires further discussion

**Comment by chriszs** [comment]
Oh, no, sorry, I mean it retains the records, but not the category metadata. I think you do want to retain the records, because there's a large amount of layoff reporting that doesn't meet WARN.
