### ISSUE TITLE
Fix VA: Find out the meaning of address fields

### ISSUE THREAD

**Issue by codyhxyz** [biglocalnews/warn-scraper#203]
Ask VA ppl the difference between:
-"Location/City" and "Location State" fields 
(seems to be associated with the business, and all but like one entry are in Virginia. Why do they have a Washington, DC entry??) 

-"Company Address 1", "Company Address 2", and "City/Town".
(seems to be associated with the HQ of the business, and many of these list different states. probably not useful for our purposes but it would be good to ask clarification about what these exist for.)

See the [data interview document](https://github.com/biglocalnews/bln-onboarding/blob/main/data_interview.md) in the BLN-onboarding repo about reaching out to an agency for information.

**Comment by palewire** [comment]
DC borders VA. The company addresses are HQs. The Locations are the sites where the jobs are lost.
