### ISSUE TITLE
Extend download_file() functionality in utils.py

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/warn-scraper#217]
Add path creation for a parent folder with Path() , e.g.:

    cache_state = Path(cache_dir, 'co')
    cache_state.mkdir(parents=True, exist_ok=True)

**Comment by palewire** [comment]
We should probably also introduce stricter typing of the inputs on this function as well. To pull this off, we might want to ensure that all `local_path` inputs are Path objects.
