### ISSUE TITLE
Fix CO: Coax agency into correcting headers

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/warn-scraper#219]
CO should be made aware that their 2017 data has their headers in kinda the wrong place.
![image](https://user-images.githubusercontent.com/20691507/128551671-cf62c460-5401-4965-aea3-a3017a712630.png)

**Comment by palewire** [comment]
There's a good hunk of commented out code hanging out in this scraper that we should figure out what we're doing with. Probably shouldn't sit in the main branch like that.

**Comment by palewire** [comment]
The issues raised here can be addressed in the reopened #65.
