### ISSUE TITLE
Fix CO: Reconcile columns between years and handle incomplete rows

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/warn-scraper#221]
- [x] CO scraper export has multiple blank lines (probably between years), despite checking for empty rows before appending. why?
- [ ] 2021 needs to merge permanent_layoffs, temporary_layoffs and furloughs columns. merge them all into total_layoffs, see docs/co.md to see the correspondence about this. we are merging these columns so the final output has consistent data between years.

- [ ] why is there a row that is blank save for the # of layoffs: '3330'

-a 'nice-to-have' is changing from the hard-coded url strategy to scraping each years' url off the website. however, this would require diverting from the hard-coded headers strategy that we have used to navigate having multiple different headers in different years.

**Comment by palewire** [comment]
The issues raised here can be addressed in the reopened #65.
