### ISSUE TITLE
Catalog and track how many states are done

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#250]

**Comment by zstumgoren** [comment]
+1 on a simple overview of the states that are completed. Heck, even a simple HTML table showing status would be great, perhaps with links to the state-specific docs pages we've been using to track state status in `docs/`.

Also, fwiw, there's a lot of workflow-related info in those state-specific doc pages (e.g. call logs with agency contacts) that really belong elsewhere such as a private GDoc or some other locale. Not sure if that deserves a separate ticket, but cleaning up those pages has been an unwritten ToDo for a while...
