### ISSUE TITLE
Refactor CLI to use `click`

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#287]

**Comment by palewire** [comment]
The testing is the big thing to look for.

**Comment by zstumgoren** [comment]
Re tests, Click has [CliRunner](https://click.palletsprojects.com/en/7.x/testing/?[highlight=clirunner). And in other projects such as court-scraper we've been using vcrpy where possible (typically when using requests). Don't think any of these warn scrapers use/require Selenium yet, but that's usually when the testing gets more cumbersome...

**Comment by palewire** [comment]
Thanks for the tip. Take a look at #303, where I switched to click and 100% of the existing tests pass. What new CLI tests with click would you want to see added to feel that this hole was filled?
