### ISSUE TITLE
Fix CT scraper

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#301]
Won't the Connecticut scraper need some way to autogenerate the current year to work into the future?

**Comment by stucka** [comment]
There's some code in the Florida scraper that might work as a model for Connecticut, if that helps.

**Comment by palewire** [comment]
@stucka, if you have an idea for a patch, I'd love to see it.

**Comment by palewire** [comment]
@stucka, what do you say?

**Comment by zstumgoren** [comment]
@palewire One other thing to note. For all these states, we also typically put in a fresh call to the source agency to see if the current site is truly the best possible online data source. I can't recall if our interns over the summer had a chance to circle back to CT in particular (I don't see any state-level docs for CT), but it might be worth doing so before knocking out this future-proofing patch

**Comment by palewire** [comment]
Fixes #351
