### ISSUE TITLE
Does the cache_dir input to scrape functions need to be optional?

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#326]
Can't we just pass the default dir to all functions? Is there a case where it needs to be `None`?

**Comment by zstumgoren** [comment]
Sounds like a good idea to have cache_dir as default to all functions, even if there are "straggler" scrapers where we haven't applied the convention of caching raw source file(s). For example, [ak.py](https://github.com/biglocalnews/warn-scraper/blob/3d9b60ae6f16fc07372700802f274ca643f64f67/warn/scrapers/ak.py) appears to request and process a single HTML page in memory and then simply writes `exports/ak.csv`.

Not sure how many (if any) other states bypass cache in this way, but making the cache dir a non-optional default for all scrapers, even if the caching convention is not yet applied, seems like a helpful nudge in the right direction.
