### ISSUE TITLE
Test GH Discussions for real-time convos with contributors?

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/warn-scraper#357]
Haven't used GH Discussions yet but wondering if we should try it for real-time comms that don't yet rise to Issue status.  @palewire @chriszs @stucka Any thoughts on how livable/user-friendly Discussions are? Open to other options such as Gitter, Slack channel on NewsNerdery, or just sticking with Issues for now. Thoughts?

**Comment by chriszs** [comment]
The React project moved some of their communication over to [discussions](https://github.com/reactwg/react-18/discussions). I don't have strong feelings.
