### ISSUE TITLE
Abstract HTML table parsing into a util function

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#368]
This is becoming a pattern used in #324, #361, #362, #363, #359, #365, #364. I see no reason it can't be abstracted into a shared util. Pandas has `read_html` for this purpose, but that's been removed (#345).

**Comment by chriszs** [comment]
(Yes, I'm willing to contribute this.)

**Comment by palewire** [comment]
Sure. Let's do it.

**Comment by palewire** [comment]
#438 added an Excel parsing util that could serve as a model/challenge.

**Comment by stucka** [comment]
@chriszs , I think I'm missing it?
