### ISSUE TITLE
CI fails on PRs on test PyPi release

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#369]
When I push to a PR branch I get an intimidating error from the GitHub Action that "test PyPi release" failed. It looks like this:

> Content received from server:
> 39
> <html>
> 40
>  <head>
> 41
>   <title>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</title>
> 42
>  </head>
> 43
>  <body>
> 44
>   <h1>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</h1>
> 45
>   Access was denied to this resource.<br/><br/>
> 46
> Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.
> 47
> 
> 48
> 
> 49
>  </body>
> 50
> </html>
> 51
> HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
> 52
> Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.

This makes it hard to distinguish failing builds.

**Comment by palewire** [comment]
I think we need to allow outside PR Actions to access the GitHub secret with our PyPI token.

**Comment by palewire** [comment]
Will look into it.
