### ISSUE TITLE
Fix IA: Add historical Excel file

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#435]
Current IA data goes back to 2017, but [2018 version](https://www.iowaworkforcedevelopment.gov/sites/search.iowaworkforcedevelopment.gov/files/documents/2018/WARN_20180503.xlsx) downloadable from states' website includes records dating back to 2011. Would have to deal with chronological overlap.

**Comment by palewire** [comment]
I grew up in Iowa so I feel an obligation to do this one.

**Comment by chriszs** [comment]
This is how I feel about Pennsylvania.
