### ISSUE TITLE
Add __source__ attribute to all scrapers

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#471]
It should include the name of the official source and an URL that goes to its WARN homepage. This can be used downstream to provide attribution to our users.

Example:
```python
__source__ = {
    "name": "State Department of Labor",
    "url": "https://labor.state.gov/warn/"
}
```

**Comment by chriszs** [comment]
I wonder if we can use this as a base URL in the scraper. Alternatively, I wonder if we can include a link to a source file in the data.
