### ISSUE TITLE
Fix GA: new scraper needed

### ISSUE THREAD

**Issue by esagara** [biglocalnews/warn-scraper#519]
Georgia has [changed how it is handling WARN notices](https://www.tcsg.edu/worksource/rapid-response/) and now has a new [data portal](https://www.tcsg.edu/warn-public-view/) that does not appear to be working yet. We will need to monitor and create a new scraper to handle this.

**Comment by Ash1R** [comment]
They also have archived notices, but only going back to 2018. 
[](https://www.dropbox.com/sh/ebrunrkg0mym3yz/AACfRhkNrCHIlimR30_jGS5pa?dl=0&preview=2018+GA+WARN+Filing+Report.pdf)

Should we scrape these as well?

**Comment by Ash1R** [comment]
I tried scraping the new data portal, but the the url request returns an intermediate page with a button to "skip to content".
I don't think that's the main problem, however. When loading the page in browser, the table takes a few seconds to load, so I'm guessing its not getting scraped either. Is there any way to solve this?

**Comment by stucka** [comment]
For the record, @Ash1R has a pull request here https://github.com/biglocalnews/warn-scraper/pull/530

**Comment by stucka** [comment]
Fixed with #530
