### ISSUE TITLE
Code getting stuck on AZ

### ISSUE THREAD

**Issue by sagaderisa** [biglocalnews/warn-scraper#527]
Hi - I'm running the scraping code but it's getting stuck on Arizona. Do you have some kind of timeout protocol?

**Comment by Ash1R** [comment]
When I ran the code, it took about 8 minutes but it did give a csv output.

**Comment by stucka** [comment]
@sagaderisa , we'd been running that code in production successfully until Friday, when an SSL certificate problem crept up. There's a workaround now for that, but I haven't seen the timeout problem. Please reopen the issue or open a new one if you have any problems.

**Comment by sagaderisa** [comment]
Will do - thank you!Sent from my iPhoneOn Aug 14, 2023, at 4:08 PM, Mike Stucka ***@***.***> wrote:﻿
@sagaderisa , we'd been running that code in production successfully until Friday, when an SSL certificate problem crept up. There's a workaround now for that, but I haven't seen the timeout problem. Please reopen the issue or open a new one if you have any problems.
