### ISSUE TITLE
Another round of Node updates

### ISSUE THREAD

**Issue by stucka** [biglocalnews/warn-scraper#585]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by chriszs** [comment]
Was this fixed in #611?

**Comment by stucka** [comment]
Everything seems to be fixed no, albeit after a couple rounds of patches that I've tried to better document on a private repo that uses this. I should probably open a ticket suggesting better documentation for upgrades here. Thank you, @chriszs !
