### ISSUE TITLE
Hawaii data missing

### ISSUE THREAD

**Issue by stucka** [biglocalnews/warn-scraper#608]
Hawaii's landing page at https://labor.hawaii.gov/wdc/real-time-warn-updates/ is still linked from the main WDC page, but all the per-year links are missing. Can't scrape what we can't find. Sorry, @Ash1R !

**Comment by chriszs** [comment]
I'm seeing the per-year pages, currently.

**Comment by chriszs** [comment]
Can we close this?

**Comment by stucka** [comment]
Thank you!
