### ISSUE TITLE
Consider switching to Ruff for pre-commit linting/formatting

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#623]
I noticed that pre-commit was running slowly on a minor change. I've recently checked out [Ruff](https://github.com/astral-sh/ruff), which claims "drop-in parity with [Flake8](https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-flake8), isort, and Black," each of which are separate steps in pre-commit right now, while benchmarking at much higher speeds. It also seems to have some pyupgrade compatibility.

**Comment by chriszs** [comment]
There do seem to be some deliberate differences from Back: https://docs.astral.sh/ruff/formatter/black/

In some initial testing on the codebase, the differences seemed exceedingly minor (Ruff on the right):

<img width="915" alt="Screenshot 2024-03-10 at 6 31 51 PM" src="https://github.com/biglocalnews/warn-scraper/assets/1103467/3a467d78-2a9c-42b6-93e9-e03c4be5b755">

<img width="970" alt="Screenshot 2024-03-10 at 6 31 41 PM" src="https://github.com/biglocalnews/warn-scraper/assets/1103467/99b4daf8-0e07-4db8-84ab-762c1fddc7a3">

**Comment by stucka** [comment]
Shouldn't we leave this open for review, @chriszs ? It sounds like it absolutely merits a look ... ?

**Comment by chriszs** [comment]
It does! But is there a clear path to acceptance and how do we get to a go/no-go? If the issue is going to be stale, I'd rather close it and bring it back out when the time is right so that issues reflect stuff we can act on.

**Comment by chriszs** [comment]
Re-opening because Ruff now has a complimentary package manager in uv (okay, technically they're independent, but from the same source and built the same way). Both have been [well-reviewed](https://mastodon.social/@palewire@palewi.re/113079321759715455).

**Comment by stucka** [comment]
Hey @newsroomdev , this seems like it might now be in your bailiwick?

**Comment by stucka** [comment]
I think this absolutely merits a look, but should probably be done in coordination with a general update and evaluation of the existing testing suite ... which I tried to get to months ago, and poked at, and then got pulled off.

This sounds like it may be eminently useful and practical on multiple levels. If adopted, we'll want to plan some time for implementing this into related repositories and updating the code there to fit. That might not be a heavy lift, especially WRT to the lift and testing of updating the testing suite. Thank you for bringing this, @chriszs .

**Comment by stucka** [comment]
And man ... this gives me pause. https://community.plone.org/t/drop-black-isort-flake8-and-use-ruff/16413/6

Linting is great. Breaking code is ... not. =)

**Comment by chriszs** [comment]
That's... rough. I wonder if there's a configuration where it doesn't do auto-fix errors but does lint and do (Black-equivalent) formatting. I think you can turn on specific suites of rules when running it.

**Comment by chriszs** [comment]
Ah, okay `ruff format` is the (Black-equivalent) formatter command. What we're seeing there is the `ruff check` linter with the `--fix` flag turned on.

When I run `ruff check` on this code base I get "All checks passed!" and when I run format I now get two minor formatting adjustments.

The fix of removing the variable assignment seems controversial, but not necessarily wrong. The fix of substituting the import is a little more of a head scratcher, but the way it's wrong is subtle enough to be an oversight.

I can see some discomfort with adding a tool that includes a `--fix` option that _might_ introduce an issue, but I wonder if that's going to be a frequent enough occurrence to overcome the benefits.

**Comment by chriszs** [comment]
And it is possible to use `select` and `ignore` rules to choose what to check (and therefore fix), e.g. `ruff check --select I --fix` for import sorting, or in configuration with [toml](https://docs.astral.sh/ruff/linter/#rule-selection). Though this might mean either drastically limiting what's fixed, individually excluding known problematic rules or fixing everything and then checking what changed (e.g. by staging first). That last one seems like good process anyway, and is essentially what should happen when running pre-commit, but may not be universally followed.

**Comment by chriszs** [comment]
Oh, interesting. There is also the concept of [fix safety](https://docs.astral.sh/ruff/linter/#fix-safety) in ruff (forgive me, I'm catching up in real time), in which fixes known to be unsafe are disabled by default and can be enabled with `--unsafe-fixes`. The unused import rule triggered in the cited example is [considered to be safe](https://docs.astral.sh/ruff/rules/unused-import/#fix-safety) most of the time, though it could be added to a list of unsafe fixes in configuration if we thought otherwise. There are a lot of [other potential issues](https://github.com/astral-sh/ruff/issues) in the ruff repo, though. Too many to fully assess.

Okay, so one approach here would be to add `ruff check` and `ruff format` to precommit (and CI) with `ruff check --select I --fix` taking the place of isort, and document a manual command that uses pre-commit-style staging (possibly leveraging pre-commit) to make additional auto fixes less risky.
