### ISSUE TITLE
Consider switching to pyright for type-checking

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#627]
In my experience, it is slightly better than mypy at catching typing issues (though I recall seeing some examples of issues which mypy flags but pyright does not). Here's some documentation on the differences: https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md

The upshot is that pyright, which powers VS Code's Pylance checking (which as we speak is highlighting the code with all sorts of red squiggles), is somewhat more advanced than mypy.

**Comment by stucka** [comment]
I'm game for keeping this open -- probably above my paygrade to decide this is right or not but I can run it up the flagpole?
