### ISSUE TITLE
Add GA scrape

### ISSUE THREAD

**Issue by Dilcia19** [biglocalnews/warn-scraper#63]
https://www.dol.state.ga.us/public/es/warn/searchwarns

This scrape is going to require selenium. It gives you results based on different regions which you have to select from a dropdown menu. After that, it should be pretty easy, just downloading the excel file.

**Comment by chriszs** [comment]
Didn't require Selenium in my testing. This got me the HTML for "statewide":
```sh
curl 'https://www.dol.state.ga.us/public/es/warn/searchwarns/list' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-raw 'geoArea=9&year=2021&step=search'
```

I did another request to get an Excel file, but may not be needed.

Working on a PR.
