### ISSUE TITLE
How does this compare to other sources?

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#646]
Back when this was started, there seemed to be a dearth of data about layoffs. Today, there are several websites with layoff data, some automated with "AI," some based on WARN, some specializing in specific industries, some collected from media and user reports.

They include:
* https://layoffs.fyi
* https://layoffdata.com/
* http://videogamelayoffs.com
* etc.

Presumably some small number of them are based on BLN data or scrapers, but I have yet to see any credit.

It'd be interesting to pull a subset of these and do a comparison, possibly on a docs page, to see what we can learn and find out what we may be missing.

**Comment by cephillips** [comment]
I would love that

Sent from my iPhone

On Apr 3, 2024, at 5:46 AM, Chris Zubak-Skees ***@***.***> wrote:

﻿

Back when this was started, there seemed to be a dearth of data about layoffs. Today, there are several websites with layoff data, some automated with "AI," some based on WARN, some specializing in specific industries, some collected from media and user reports.

They include:

  *   https://layoffs.fyi
  *   https://layoffdata.com/
  *   http://videogamelayoffs.com
  *   etc.

Presumably some small number of them are based on BLN data or scrapers, but I have yet to see any credit.

It'd be interesting to pull a subset of these and do a comparison, possibly on a docs page.
