### ISSUE TITLE
Add CO scrape

### ISSUE THREAD

**Issue by Dilcia19** [biglocalnews/warn-scraper#65]
https://cdle.colorado.gov/employers/layoff-separations/layoff-warn-list

WARN links lead to google spreadsheets. Download and convert to xlsx. attempt to extract and preserve link to layoff notice during ETL process.

**Comment by palewire** [comment]
While there's a great running start at the Colorado scraper, I'd like to see the issues raised in #221 and #219 resolved before we release the code. So I'm going to park the progress thus far in the [tidy-co](https://github.com/biglocalnews/warn-scraper/tree/tidy-co) branch and remove the scraper from the main branch for now.

**Comment by palewire** [comment]
Fixed by #487
