### ISSUE TITLE
Fix OH: Get historical data out of PDFs

### ISSUE THREAD

**Issue by Dilcia19** [biglocalnews/warn-scraper#72]
There's already a scraper for Ohio, however it only pulls 2020 data because that's what is available in tabular format on the website.

2019 and back are PDFs that need to be scraped and joined with the more recent data. 

As always, we should inquire about getting machine-readable historical data (as opposed to PDFs) and if possible having the agency post machine-readable files to the site for fully automated, reproducible scraping.

**Comment by chriszs** [comment]
Note that like FL (see #432) the [2015](https://jfs.ohio.gov/warn/WARN2015.stm) and [2016](https://jfs.ohio.gov/warn/WARN2016.stm) PDFs appear to be available to download, even though no longer [linked to](https://jfs.ohio.gov/warn/).
